### ISSUE TITLE
according to issue #158

### ISSUE THREAD

**Issue by vahidalvandi** [rinvex/attributes#171]
hi accroding to https://github.com/rinvex/laravel-attributes/issues/158 i add this in register provider

```
    public function register()
    {

        // Push your entity fully qualified namespace
        app('rinvex.attributes.entities')->push(Company::class);


        Attribute::typeMap([
            'varchar' => \Rinvex\Attributes\Models\Type\Varchar::class,
        ]);

    }
```

then in Company model i added this code

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    use \Rinvex\Attributes\Traits\Attributable;
}
```

i want to create a custome value to Company Model . do need to create company table ???? If true then why are we using eav?

**Comment by Omranic** [comment]
You may need to check the [EAV Model](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model) first, it's not relevant to everyone, there's specific use cases where you may need it, so if you don't know why you need it, then most probably you don't 🙂

**Comment by vahidalvandi** [comment]
@Omranic 
I use this model to build crm but I'm confused how eloquent model works I wish you had an initial demo.

**Comment by Omranic** [comment]
Hmmm, I'm not sure what exactly not clear, but if you mean Eloquent itself, then your best location to learn about it is the official documentation here https://laravel.com/docs/9.x/eloquent
